services:
  cncjs:
    image: cncjs/cncjs:latest
    privileged: true
    restart: always
    ports:
      - "8000:8000"
  mjpg-streamer:
    build: ./mjpg-streamer/mjpg-streamer-experimental
    privileged: true
    restart: always
    ports:
      - "8080:8080"
